name: Build, Test, and Publish

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - 'releases/*'
    tags:
      - '*'

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build and Test
        run: |
          make test
          make build

  publish-docker:
    name: Publish Docker Image
    needs: build-test
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ghcr.io/d8x/sgw:${{ github.ref }} -t ghcr.io/d8x/sgw:latest . --push
